/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalyticsData {
  'totalReservations' : bigint,
  'popularDishes' : Array<PopularDish>,
  'totalOrdersToday' : bigint,
  'totalRevenueToday' : bigint,
}
export type MenuCategory = { 'breads' : null } |
  { 'familyPacksNonVeg' : null } |
  { 'shakes' : null } |
  { 'curriesNonVeg' : null } |
  { 'curriesVeg' : null } |
  { 'premiumShakes' : null } |
  { 'chineseVeg' : null } |
  { 'startersNonVeg' : null } |
  { 'soupsVeg' : null } |
  { 'rice' : null } |
  { 'riceNoodlesVeg' : null } |
  { 'andhraCurries' : null } |
  { 'biryanisNonVeg' : null } |
  { 'mojitosLemonades' : null } |
  { 'startersVeg' : null } |
  { 'biryanisVeg' : null } |
  { 'beverages' : null } |
  { 'soupsNonVeg' : null } |
  { 'familyPacksVeg' : null } |
  { 'iceCream' : null } |
  { 'riceNoodlesNonVeg' : null } |
  { 'chineseNonVeg' : null };
export interface MenuItem {
  'id' : bigint,
  'name' : string,
  'isAvailable' : boolean,
  'description' : string,
  'imageUrl' : [] | [string],
  'category' : MenuCategory,
  'isVeg' : boolean,
  'price' : bigint,
}
export interface Order {
  'id' : bigint,
  'customerName' : string,
  'status' : OrderStatus,
  'createdAt' : bigint,
  'specialInstructions' : [] | [string],
  'totalAmount' : bigint,
  'address' : string,
  'phone' : string,
  'items' : Array<OrderItem>,
}
export interface OrderItem {
  'qty' : bigint,
  'itemId' : bigint,
  'name' : string,
  'price' : bigint,
}
export type OrderStatus = { 'preparing' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'ready' : null };
export interface PopularDish {
  'itemId' : bigint,
  'name' : string,
  'orderCount' : bigint,
}
export interface Reservation {
  'id' : bigint,
  'status' : ReservationStatus,
  'date' : string,
  'name' : string,
  'createdAt' : bigint,
  'time' : string,
  'email' : string,
  'specialRequest' : [] | [string],
  'phone' : string,
  'guests' : bigint,
}
export type ReservationStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'confirmed' : null };
export interface UserProfile {
  'name' : string,
  'email' : [] | [string],
  'phone' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMenuItem' : ActorMethod<
    [string, MenuCategory, bigint, boolean, string, [] | [string]],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrder' : ActorMethod<
    [string, string, string, Array<OrderItem>, bigint, [] | [string]],
    bigint
  >,
  'createReservation' : ActorMethod<
    [string, string, string, string, string, bigint, [] | [string]],
    bigint
  >,
  'deleteMenuItem' : ActorMethod<[bigint], boolean>,
  'getAllMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllReservations' : ActorMethod<[], Array<Reservation>>,
  'getAnalytics' : ActorMethod<[], AnalyticsData>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMenuItem' : ActorMethod<[bigint], [] | [MenuItem]>,
  'getOrder' : ActorMethod<[bigint], [] | [Order]>,
  'getReservation' : ActorMethod<[bigint], [] | [Reservation]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateMenuItem' : ActorMethod<
    [
      bigint,
      string,
      MenuCategory,
      bigint,
      boolean,
      string,
      [] | [string],
      boolean,
    ],
    boolean
  >,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], boolean>,
  'updateReservationStatus' : ActorMethod<[bigint, ReservationStatus], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];