/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const MenuCategory = IDL.Variant({
  'breads' : IDL.Null,
  'familyPacksNonVeg' : IDL.Null,
  'shakes' : IDL.Null,
  'curriesNonVeg' : IDL.Null,
  'curriesVeg' : IDL.Null,
  'premiumShakes' : IDL.Null,
  'chineseVeg' : IDL.Null,
  'startersNonVeg' : IDL.Null,
  'soupsVeg' : IDL.Null,
  'rice' : IDL.Null,
  'riceNoodlesVeg' : IDL.Null,
  'andhraCurries' : IDL.Null,
  'biryanisNonVeg' : IDL.Null,
  'mojitosLemonades' : IDL.Null,
  'startersVeg' : IDL.Null,
  'biryanisVeg' : IDL.Null,
  'beverages' : IDL.Null,
  'soupsNonVeg' : IDL.Null,
  'familyPacksVeg' : IDL.Null,
  'iceCream' : IDL.Null,
  'riceNoodlesNonVeg' : IDL.Null,
  'chineseNonVeg' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'qty' : IDL.Nat,
  'itemId' : IDL.Nat,
  'name' : IDL.Text,
  'price' : IDL.Nat,
});
export const MenuItem = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'imageUrl' : IDL.Opt(IDL.Text),
  'category' : MenuCategory,
  'isVeg' : IDL.Bool,
  'price' : IDL.Nat,
});
export const OrderStatus = IDL.Variant({
  'preparing' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'ready' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'createdAt' : IDL.Int,
  'specialInstructions' : IDL.Opt(IDL.Text),
  'totalAmount' : IDL.Nat,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
});
export const ReservationStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Reservation = IDL.Record({
  'id' : IDL.Nat,
  'status' : ReservationStatus,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'time' : IDL.Text,
  'email' : IDL.Text,
  'specialRequest' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
  'guests' : IDL.Nat,
});
export const PopularDish = IDL.Record({
  'itemId' : IDL.Nat,
  'name' : IDL.Text,
  'orderCount' : IDL.Nat,
});
export const AnalyticsData = IDL.Record({
  'totalReservations' : IDL.Nat,
  'popularDishes' : IDL.Vec(PopularDish),
  'totalOrdersToday' : IDL.Nat,
  'totalRevenueToday' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMenuItem' : IDL.Func(
      [IDL.Text, MenuCategory, IDL.Nat, IDL.Bool, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrder' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(OrderItem),
        IDL.Nat,
        IDL.Opt(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'createReservation' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Opt(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'deleteMenuItem' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllReservations' : IDL.Func([], [IDL.Vec(Reservation)], ['query']),
  'getAnalytics' : IDL.Func([], [AnalyticsData], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMenuItem' : IDL.Func([IDL.Nat], [IDL.Opt(MenuItem)], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
  'getReservation' : IDL.Func([IDL.Nat], [IDL.Opt(Reservation)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateMenuItem' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        MenuCategory,
        IDL.Nat,
        IDL.Bool,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Bool,
      ],
      [IDL.Bool],
      [],
    ),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [IDL.Bool], []),
  'updateReservationStatus' : IDL.Func(
      [IDL.Nat, ReservationStatus],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const MenuCategory = IDL.Variant({
    'breads' : IDL.Null,
    'familyPacksNonVeg' : IDL.Null,
    'shakes' : IDL.Null,
    'curriesNonVeg' : IDL.Null,
    'curriesVeg' : IDL.Null,
    'premiumShakes' : IDL.Null,
    'chineseVeg' : IDL.Null,
    'startersNonVeg' : IDL.Null,
    'soupsVeg' : IDL.Null,
    'rice' : IDL.Null,
    'riceNoodlesVeg' : IDL.Null,
    'andhraCurries' : IDL.Null,
    'biryanisNonVeg' : IDL.Null,
    'mojitosLemonades' : IDL.Null,
    'startersVeg' : IDL.Null,
    'biryanisVeg' : IDL.Null,
    'beverages' : IDL.Null,
    'soupsNonVeg' : IDL.Null,
    'familyPacksVeg' : IDL.Null,
    'iceCream' : IDL.Null,
    'riceNoodlesNonVeg' : IDL.Null,
    'chineseNonVeg' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'qty' : IDL.Nat,
    'itemId' : IDL.Nat,
    'name' : IDL.Text,
    'price' : IDL.Nat,
  });
  const MenuItem = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'imageUrl' : IDL.Opt(IDL.Text),
    'category' : MenuCategory,
    'isVeg' : IDL.Bool,
    'price' : IDL.Nat,
  });
  const OrderStatus = IDL.Variant({
    'preparing' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'ready' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'createdAt' : IDL.Int,
    'specialInstructions' : IDL.Opt(IDL.Text),
    'totalAmount' : IDL.Nat,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
  });
  const ReservationStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Reservation = IDL.Record({
    'id' : IDL.Nat,
    'status' : ReservationStatus,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'time' : IDL.Text,
    'email' : IDL.Text,
    'specialRequest' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
    'guests' : IDL.Nat,
  });
  const PopularDish = IDL.Record({
    'itemId' : IDL.Nat,
    'name' : IDL.Text,
    'orderCount' : IDL.Nat,
  });
  const AnalyticsData = IDL.Record({
    'totalReservations' : IDL.Nat,
    'popularDishes' : IDL.Vec(PopularDish),
    'totalOrdersToday' : IDL.Nat,
    'totalRevenueToday' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMenuItem' : IDL.Func(
        [
          IDL.Text,
          MenuCategory,
          IDL.Nat,
          IDL.Bool,
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrder' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(OrderItem),
          IDL.Nat,
          IDL.Opt(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'createReservation' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Opt(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'deleteMenuItem' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllReservations' : IDL.Func([], [IDL.Vec(Reservation)], ['query']),
    'getAnalytics' : IDL.Func([], [AnalyticsData], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMenuItem' : IDL.Func([IDL.Nat], [IDL.Opt(MenuItem)], ['query']),
    'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
    'getReservation' : IDL.Func([IDL.Nat], [IDL.Opt(Reservation)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateMenuItem' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          MenuCategory,
          IDL.Nat,
          IDL.Bool,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Bool,
        ],
        [IDL.Bool],
        [],
      ),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [IDL.Bool], []),
    'updateReservationStatus' : IDL.Func(
        [IDL.Nat, ReservationStatus],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };